<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
 $me = $this;
?>
<nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand align-middle ml-3" href="<?= $me->url('app'); ?>">
                <h2><?= _APP_NAME_; ?></h2>
            </a>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $me->url('app'); ?>">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $me->url('app'); ?>">Shinergy <span class="sr-only"></span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $me->url('app'); ?>">MakeFlow <span class="sr-only"></span></a>
                </li>
            </ul> -->
        </div>
    </div>
</nav>