<div x-cloak x-data="filter" x-bind="event" x-show="show" class="z-50 fixed w-full flex justify-center inset-0">
    <div @click="cancelFilter()" class="w-full h-full bg-bluegray-900 bg-opacity-70 z-0 absolute inset-0"></div>
    <div class="mx-auto container">
        <div class="flex items-center justify-center h-full w-full">
            <div class="bg-white rounded-md shadow fixed overflow-y-auto sm:h-auto w-3/4">
                <div class="px-5 py-4">
                    <div class="w-full grid grid-cols-6 mb-5">
                        <div class="col-span-1 font-bold">
                            FIELD
                        </div>
                        <div class="col-span-2 font-bold pl-3">
                            CONDITION
                        </div>
                        <div class="col-span-3 whitespace-nowrap font-bold pl-3">
                            VALUE (comma separated)
                        </div>
                    </div>
                    <template x-for="(fld,idx) in field">
                        <div class="w-full grid grid-cols-6 my-3">
                            <div class="col-span-1 pt-2" x-text="fld.label"></div>
                            <div class="col-span-2 pl-3">
                                <select class="tom-select-search" :id="'filtercond-'+idx" x-model="fld.cond">
                                    <option value="none" class="whitespace-nowrap">None</option>
                                    <option value="equal" class="whitespace-nowrap">Equal</option>
                                    <option value="notequal" class="whitespace-nowrap">Not Equal</option>
                                    <option value="like" class="whitespace-nowrap">Like</option>
                                    <option value="notlike" class="whitespace-nowrap">Not Like</option>
                                    <option value="prefix" class="whitespace-nowrap">Prefix</option>
                                    <option value="notprefix" class="whitespace-nowrap">Not Prefix</option>
                                    <option value="suffix" class="whitespace-nowrap">Suffix</option>
                                    <option value="notsuffix" class="whitespace-nowrap">Not Suffix</option>
                                </select>
                            </div>
                            <div class="col-span-3 pl-3">
                                <template x-if="fld.type==='text'">
                                    <input x-model="fld.val" :id="'filterval-'+idx" class="tom-input-tag w-full focus:ring-2 focus:ring-bluegray-400 focus:outline-none placeholder-gray-500 text-sm leading-none text-gray-800 bg-white border rounded border-gray-200" />
                                </template>
                                <template x-if="fld.type==='select'">
                                    <select class="tom-select-search" :id="'filterval-'+idx" x-model="fld.val">
                                        <option value="none" class="whitespace-nowrap">None</option>
                                        <template x-for="sel in fld.select">
                                            <option class="whitespace-nowrap" :value="sel.val" x-text="sel.label">
                                            </option>
                                        </template>
                                    </select>
                                </template>
                            </div>
                        </div>
                    </template>
                    <div class="flex items-center justify-end mt-20 gap-x-2">
                        <button @click="cancelFilter()" role="button" aria-label="close button" class="focus:ring-2 focus:ring-offset-2 focus:bg-gray-600 focus:ring-gray-500 focus:outline-none px-3 py-1 bg-gray-500 hover:bg-gray-400 shadow rounded text-sm text-white">Cancel</button>
                        <button @click="updateFilter()" role="button" class="focus:ring-2 focus:ring-offset-2 focus:ring-blue-800 focus:outline-none px-3 py-1 bg-blue-700 hover:bg-opacity-80 shadow rounded text-sm text-white">Update
                            Filter</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div x-cloak x-data="create" x-show="show" x-bind="bind.self" class="z-50 fixed w-full flex justify-center inset-0">
    <div @click="cancelCreate()" class="w-full h-full bg-bluegray-900 bg-opacity-70 z-0 absolute inset-0"></div>
    <div class="mx-auto container">
        <div class="flex items-center justify-center h-full w-full">
            <div class="bg-white rounded-md shadow fixed overflow-y-auto sm:h-auto w-1/2">
                <div class="px-5 py-4">
                    <div class="">
                        <div>
                            <h3 x-text="title" :class="{'bg-green-700':data.id===null,'bg-indigo-700':data.id!==null}" class="text-xl leading-6 font-medium text-white py-2 px-2 rounded">
                            </h3>
                            <p class="mt-1 text-sm text-gray-500"></p>
                        </div>
                        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4">
                            <div class="col-span-1">
                                <label class="block text-sm font-medium text-gray-700">
                                    Layout Name
                                </label>
                                <div class="mt-1 relative rounded-md shadow-sm">
                                    <input x-bind="bind.name.input" x-model="data.name" type="text" class="form-input shadow-sm block w-full sm:text-sm rounded-md">
                                    <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                                        <svg x-show="name_msg!==''" class="h-5 w-5 text-red-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                                        </svg>
                                    </div>
                                </div>
                                <div class="relative">
                                    <p x-show="name_msg!==''" class="absolute mt-2 text-xs text-red-600" x-html="name_msg"></p>
                                </div>
                            </div>

                            <div class="col-span-1">
                                <label class="block text-sm font-medium text-gray-700">
                                    Status
                                </label>
                                <div class="mt-3">
                                    <div class="flex items-center">
                                        <span class="mr-3">
                                            <span x-bind="bind.status.label1" class="text-sm">Inactive</span>
                                        </span>
                                        <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
                                        <button type="button" x-bind="bind.status.btn" class="relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2" role="switch" aria-checked="false">
                                            <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
                                            <span aria-hidden="true" x-bind="bind.status.btn_span" class="pointer-events-none inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200"></span>
                                        </button>
                                        <span class="ml-3">
                                            <span x-bind="bind.status.label2" class="text-sm">Active</span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex items-center justify-end mt-10 gap-x-2">
                        <button role="button" aria-label="close button" @click="cancelCreate()" class="focus:ring-2 focus:ring-offset-2 focus:bg-gray-600 focus:ring-gray-500 focus:outline-none px-3 py-1 bg-gray-500 hover:bg-gray-400 shadow rounded text-sm text-white">Cancel</button>
                        <button @click="submitCreate()" role="button" :class="{'focus:ring-green-800 bg-green-700':data.id===null,'focus:ring-indigo-800 bg-indigo-700':data.id!==null}" class="focus:ring-2 focus:ring-offset-2 focus:outline-none px-3 py-1 hover:bg-opacity-80 shadow rounded text-sm text-white">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>