const colors = require('tailwindcss/colors');
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
  content: [
    './module/**/view/**/*.phtml',
    './views/**/*.phtml',
    './src/**/*.js',
    './public/js/**/*.js',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['cairo', 'Inter var', ...defaultTheme.fontFamily.sans],
      },
    },
    screens: {
      xs: '475px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      'phone': '475px',
      'tablet': '640px',
      'laptop': '1024px',
      'desktop': '1280px',
    },
    colors: {
      ebis: {
        a: '#6784FD',
        b: '#6CD3FF',
        c: '#5EADFE',
        d: '#1464BC',
        e: '#f7b63d',
        f: '#FF55A4',
        g: '#46A9D5',
        h: '#4D7093',
        i: '#80A1C3',
        j: '#DBCFCE',
        k: '#FCFCFC',
        l: '#E6F0FF',
        m: '#00717D',
        n: '#CDDDF8',
        o: "#53d4b0"
      },
      light: 'var(--light)',
      dark: 'var(--dark)',
      darker: 'var(--darker)',
      primary: {
        DEFAULT: 'var(--color-primary)',
        50: 'var(--color-primary-50)',
        100: 'var(--color-primary-100)',
        light: 'var(--color-primary-light)',
        lighter: 'var(--color-primary-lighter)',
        dark: 'var(--color-primary-dark)',
        darker: 'var(--color-primary-darker)',
      },
      secondary: {
        DEFAULT: colors.fuchsia[600],
        50: colors.fuchsia[50],
        100: colors.fuchsia[100],
        light: colors.fuchsia[500],
        lighter: colors.fuchsia[400],
        dark: colors.fuchsia[700],
        darker: colors.fuchsia[800],
      },
      success: {
        DEFAULT: colors.green[600],
        50: colors.green[50],
        100: colors.green[100],
        light: colors.green[500],
        lighter: colors.green[400],
        dark: colors.green[700],
        darker: colors.green[800],
      },
      warning: {
        DEFAULT: colors.orange[600],
        50: colors.orange[50],
        100: colors.orange[100],
        light: colors.orange[500],
        lighter: colors.orange[400],
        dark: colors.orange[700],
        darker: colors.orange[800],
      },
      danger: {
        DEFAULT: colors.red[600],
        50: colors.red[50],
        100: colors.red[100],
        light: colors.red[500],
        lighter: colors.red[400],
        dark: colors.red[700],
        darker: colors.red[800],
      },
      info: {
        DEFAULT: colors.cyan[600],
        50: colors.cyan[50],
        100: colors.cyan[100],
        light: colors.cyan[500],
        lighter: colors.cyan[400],
        dark: colors.cyan[700],
        darker: colors.cyan[800],
      },
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      bluegray: colors.slate,
      slate: colors.slate,
      coolgray: colors.gray,
      gray: colors.gray,
      truegray: colors.neutral,
      neutral: colors.neutral,
      warmgray: colors.stone,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      yellow: colors.yellow,
      lime: colors.lime,
      green: colors.green,
      emerald: colors.emerald,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      violet: colors.violet,
      indigo: colors.indigo,
      purple: colors.purple,
      fuchsia: colors.fuchsia,
      rose: colors.rose,
      pink: colors.pink,
      mygreen: {
        light: "#A7FFA4",
        DEFAULT: "#4CAF50",
        dark: "#144D1D",
        hover: "#4caf5140"
      }
    },
    animation: {
      none: 'none',
      spin: 'spin 1s linear infinite',
      ping: 'ping 1s cubic-bezier(0, 0, 0.2, 1) infinite',
      pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      bounce: 'bounce 1s infinite',
    },
  },
  plugins: [
    // require('@tailwindcss/forms'),
    require("@tailwindcss/forms")({
      strategy: 'class',
    }),
    require("tailwind-gradient-mask-image"),
    require('@tailwindcss/line-clamp'),
    require('@tailwindcss/aspect-ratio'),
    require('tailwind-scrollbar')
  ]
};
