ARG POSTGRES_VERSION=14.2
FROM postgres:${POSTGRES_VERSION}-alpine

# RUN mkdir -p /postgresql && chmod 777 /postgresql
# RUN mkdir -p /postgresql/data && chmod 777 /postgresql/data
# RUN mkdir -p /postgresql/data/pgdata && chmod 777 /postgresql/data/pgdata

# RUN chown -R postgres /postgresql
# RUN chown -R postgres /postgresql/data
# RUN chown -R postgres /postgresql/data/pgdata

# USER postgres