<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
$me = $this;
// !d($me);
?>
<!-- blank layout -->
<?=$me->doctype()?>
<?php
$content = $me->content;
// zdebug($content);die();
$vars = $me->vars();
// !d($vars);die();
$_vars = $vars['_vars_']??[];
$module = $_vars['module']??"";
$controller = $_vars['controller']??"";
$controller = str_replace("Controller", "", $controller);
$action = $_vars['action']??"";
$layout = $_vars['layout']??"";
// !d($layout);die();
$active_menu = $me->active_menu??"";
unset($vars['content']);
?>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <?=$me->headMeta()?>
  <?=$me->headTitle()->setAutoEscape(false)?>
  <?=$me->headLink(['rel' => 'shortcut icon', 'type' => 'image/gif', 'href' => $me->basePath() . '/img/fav.ico']);?>

  <?=$me->partial('partial-css.phtml', ['_vars' => $_vars,'_module'=>$module,'_controller'=>$controller,'_action'=>$action,'_layout'=>$layout,'_active_menu'=>$active_menu]);?>

  <?=$me->headStyle()?>
</head>

<body>
  <?=$content;?>

  <!-- Scripts -->
  <?=$me->headScript();?>

  <?=$me->partial('partial-js.phtml', ['_vars' => $_vars,'_module'=>$module,'_controller'=>$controller,'_action'=>$action,'_layout'=>$layout,'_active_menu'=>$active_menu]);?>
  <?=$me->inlineScript()?>
</body>

</html>