<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
$me = $this;
// !d($me);
$headScript = $me->headScript();
$headScript->appendFile('/js-lib/echart-5.3.2/echarts.min.js');
$headScript->appendFile('/js-lib/echart-5.3.2/theme/ebis-a.js');
$headScript->appendFile('/js-lib/flatpickr/flatpickr.min.js');
$headScript->appendFile('/js-lib/flatpickr/plugins/monthSelect/index.js');
/** @var \Laminas\View\Helper\HeadStyle $headStyle */
$headStyle = $this->headLink();
$headStyle->appendStylesheet("/js-lib/flatpickr/flatpickr.min.css");
$headStyle->appendStylesheet("/js-lib/flatpickr/plugins/monthSelect/style.css");
$headStyle->appendStylesheet("/js-lib/flatpickr/themes/material_green.css");
?>
<?php $this->headStyle()->captureStart() ?>
.echart div{
    margin: 0px auto;
}
<?php 
$this->headStyle()->captureEnd();
$headScript = $me->headScript();
$headScript->captureStart();
?>
const _reg = "<?= $this->reg;?>";
const _witel = <?= json_encode($this->witel);?>;
<?php
$headScript->captureEnd();
?>
<div class="flex flex-nowrap place-content-center justify-center items-stretch content-center justify-self-center items-center md:justify-end p-2 mb-1">
  <div class="shrink "><input id="startdate" type="text" placeholder="Start Date" class="year-month border text-center border-2 w-[150px] border-ebis-a form-input text-sm py-1 px-2 rounded-l-md"></div>
  <div class="shrink bg-ebis-a text-ebis-k font-medium text-sm text-center pt-1 px-2">to</div>
  <div class="shrink"><input id="enddate" type="text" placeholder="End Date" class="year-month border border-2 text-center w-[150px] border-ebis-a form-input text-sm py-1 px-2 rounded-r-md"></div>
  <div class="grow md:grow-0 ml-3"><button class="rounded-md text-md bg-ebis-a hover:bg-ebis-c text-ebis-l h-full px-2 py-1 w-full">Search</button></div>
</div>
<div class="grid grid-cols-1 md:grid-cols-12 gap-2">
    <div class="col-span-1 md:col-span-8 grid grid-cols-1 gap-1">
        <div class="col-span-1 bg-ebis-k rounded-md p-2 border border-gray-200">
            <div class="text-center mb-3 font-medium">        
                <?php 
                if($this->reg==="nasional"){
                    echo "NASIONAL";    
                } else {
                    echo "REGIONAL ".$this->reg;    
                } ?>
                PROFITABILITY TREND
            </div>
            <div class="grid grid-cols-1 md:grid-cols-3">
                <div class="col-span-1 text-center relative">
                    <div class="absolute w-full h-full">
                        <div class="-mt-[20px] flex h-full justify-center flex-nowrap content-center items-center">
                            <div class="">
                                <svg class="w-6 h-6" fill="#53d47a" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-8.707l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13a1 1 0 102 0V9.414l1.293 1.293a1 1 0 001.414-1.414z" clip-rule="evenodd"></path></svg>
                            </div>
                            <div class="">
                                <h1 class="text-[30px] font-bold" id="chart-reg-label1-gauge">XXX</h1>
                            </div>    
                        </div>
                    </div>
                    <div class="absolute w-full h-full">
                        <div class="mt-[10px] flex h-full justify-center flex-nowrap content-center items-center">
                            <div class="">
                                <svg class="w-4 h-4" fill="#fa1f1f" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v3.586L7.707 9.293a1 1 0 00-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 10.586V7z" clip-rule="evenodd"></path></svg>
                            </div>
                            <div class="">
                                <h1 class="text-[20px] font-medium" id="chart-reg-label2-gauge">15%</h1>
                            </div>    
                        </div>
                    </div>
                    <div id="chart-reg-trend-gauge" class="drop-shadow-lg echart mx-auto min-w-full w-full min-h-[150px] h-[35vh]"></div>
                </div>
                <div class="col-span-1 md:col-span-2 text-center">
                    <div id="chart-reg-trend-line" class="echart mx-auto min-w-full w-full min-h-[150px] h-[35vh]"></div>
                </div>
            </div>
        </div>
        <?php if(count($this->witel)>0){ ?>
        <div class="col-span-1 bg-ebis-k rounded-md p-2 border border-gray-200">
            <div class="text-center mb-3 font-medium">PROFITABILITY WITEL</div>
            <div class="flex flex-wrap justify-center space-x-2 space-x-reverse space-y-2 space-y-reverse p-3">
                <?php foreach($this->witel as $k=>$v){ ?>
                <div class="text-center w-[150px]">
                    <div class="text-center relative w-full">
                        <div class="absolute w-full h-full">
                            <div class="flex h-full justify-center flex-nowrap content-center items-center gap-1">
                                <div class="text-right">
                                    <h1 class="text-[25px] font-bold" id="chart-witel<?= $v; ?>-label1-gauge">XXX</h1>
                                    <h1 class="-mt-[15px] text-[25px] font-medium">%</h1>
                                </div>
                                <div class="text-left">
                                    <h1 class="text-[10px] font-medium">Rev.</h1>
                                    <h1 class="-mt-[5px] text-[10px] font-medium">Margin.</h1>
                                </div>    
                            </div>
                        </div>
                        <div id="chart-witel<?= $v; ?>-trend-gauge" class="drop-shadow-lg echart mx-auto min-w-full w-full min-h-[150px]"></div>
                    </div>
                    <div id="chart-witel<?= $v; ?>-label2-gauge" class="drop-shadow-lg font-bold text-sm whitespace-pre-wrap w-full -mt-7"><?= $k; ?></div>
                </div>
                <?php } ?>
            </div>
        </div>
        <?php } ?>
        <?php if($this->reg==="nasional"){ ?>
        <div class="col-span-1 bg-ebis-k rounded-md p-2 border border-gray-200">
            <div class="text-center mb-3 font-medium">PROFITABILITY REGIONAL</div>
            <div class="flex flex-wrap justify-center space-x-2 space-x-reverse space-y-2 space-y-reverse p-3">
                <?php for($i=1;$i<8;$i++){ ?>
                <div class="text-center w-[150px]">
                    <div class="text-center relative w-full">
                        <div class="absolute w-full h-full">
                            <div class="flex h-full justify-center flex-nowrap content-center items-center gap-1">
                                <div class="text-right">
                                    <h1 class="text-[25px] font-bold" id="chart-reg<?= $i; ?>-label1-gauge">XXX</h1>
                                    <h1 class="-mt-[15px] text-[25px] font-medium">%</h1>
                                </div>
                                <div class="text-left">
                                    <h1 class="text-[10px] font-medium">Rev.</h1>
                                    <h1 class="-mt-[5px] text-[10px] font-medium">Margin.</h1>
                                </div>    
                            </div>
                        </div>
                        <div id="chart-reg<?= $i; ?>-trend-gauge" class="drop-shadow-lg echart mx-auto min-w-full w-full min-h-[150px]"></div>
                    </div>
                    <div id="chart-reg<?= $i; ?>-label2-gauge" class="drop-shadow-lg font-bold text-sm whitespace-pre-wrap w-full -mt-7">REGIONAL <?= $i; ?></div>
                </div>
                <?php } ?>
            </div>
        </div>
        <?php } ?>
    </div>
    <div class="h-fit col-span-1 md:col-span-4 bg-ebis-k rounded-md p-3 border border-gray-200">
        <div class="text-center mb-3 font-medium">PROFITABILITY PRODUCT</div>
        <div class="grid grid-cols-1 gap-4">
            <div class="bg-gradient-to-b from-ebis-b via-ebis-b to-ebis-l border drop-shadow-md p-3 rounded-xl">
                <div class="flex justify-around flex-nowrap content-center items-center gap-1">
                    <div class="text-left">
                        <h1 class="text-[20px] font-bold">Connectivity</h1>
                        <h1 class="-mt-[10px] text-[20px] font-medium">80 %</h1>
                    </div>
                    <div class="text-left">
                        <h1 class="text-[15px] font-medium">Rev.</h1>
                        <h1 class="-mt-[5px] text-[15px] font-medium">Margin.</h1>
                    </div>    
                </div>
                <div class="relative h-3 w-full rounded-md border-ebis-c border mt-3 ">
                    <div class="drop-shadow-lg absolute block rounded-md h-full w-full bg-ebis-k "></div>
                    <div class="absolute block rounded-md h-full w-1/2 bg-gradient-to-r from-ebis-h to-ebis-a"></div>
                </div>
                <div class="grid grid-cols-1 gap-2 mt-3">
                    <div class="rounded-sm p-1 bg-ebis-k grid grid-cols-1 md:grid-cols-2 gap-1 items-center place-content-between">
                        <div class="text-xs">Conn 1</div>
                        <div class="">
                            <div class="relative h-4 w-full rounded-sm ">
                                <div class="absolute block rounded-sm h-full w-full bg-ebis-n "></div>
                                <div class="absolute block rounded-sm h-full w-1/2 bg-gradient-to-r from-[#5dabd8] via-[#53d4b0] to-[#6687f0]"></div>
                            </div>
                        </div>
                    </div>
                    <div class="rounded-sm p-1 bg-ebis-k grid grid-cols-1 md:grid-cols-2 gap-1 items-center place-content-between">
                        <div class="text-xs">Conn 2</div>
                        <div class="">
                            <div class="relative h-4 w-full rounded-sm">
                                <div class="absolute block rounded-sm h-full w-full bg-ebis-n "></div>
                                <div class="absolute block rounded-sm h-full w-3/4 bg-gradient-to-r from-[#5dabd8] via-[#53d4b0] to-[#6687f0]"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bg-gradient-to-b from-ebis-b via-ebis-b to-ebis-l border drop-shadow-md p-3 rounded-xl">
                <div class="flex justify-around flex-nowrap content-center items-center gap-1">
                    <div class="text-left">
                        <h1 class="text-[20px] font-bold">Mansol</h1>
                        <h1 class="-mt-[10px] text-[20px] font-medium">80 %</h1>
                    </div>
                    <div class="text-left">
                        <h1 class="text-[15px] font-medium">Rev.</h1>
                        <h1 class="-mt-[5px] text-[15px] font-medium">Margin.</h1>
                    </div>    
                </div>
                <div class="relative h-3 w-full rounded-md border-ebis-c border mt-3 ">
                    <div class="drop-shadow-lg absolute block rounded-md h-full w-full bg-ebis-k "></div>
                    <div class="absolute block rounded-md h-full w-1/2 bg-gradient-to-r bg-gradient-to-r from-[#5dabd8] via-[#53d4b0] to-[#6687f0]"></div>
                </div>
            </div>
            <div class="bg-gradient-to-b from-ebis-b via-ebis-b to-ebis-l border drop-shadow-md p-3 rounded-xl">
                <div class="flex justify-around flex-nowrap content-center items-center gap-1">
                    <div class="text-left">
                        <h1 class="text-[20px] font-bold">POTS</h1>
                        <h1 class="-mt-[10px] text-[20px] font-medium">80 %</h1>
                    </div>
                    <div class="text-left">
                        <h1 class="text-[15px] font-medium">Rev.</h1>
                        <h1 class="-mt-[5px] text-[15px] font-medium">Margin.</h1>
                    </div>    
                </div>
                <div class="relative h-3 w-full rounded-md border-ebis-c border mt-3 ">
                    <div class="drop-shadow-lg absolute block rounded-md h-full w-full bg-ebis-k "></div>
                    <div class="absolute block rounded-md h-full w-1/2 bg-gradient-to-r bg-gradient-to-r from-[#5dabd8] via-[#53d4b0] to-[#6687f0]"></div>
                </div>
            </div>
            <button class="p-2 bg-ebis-a hover:bg-ebis-c text-ebis-k rounded-md">Download Data</button>
        </div>
    </div>
</div>