
        <div class="flex items-center justify-center py-8 px-4">
            <div class="md:w-96 w-full px-5 py-4 rounded shadow-lg bg-white dark:bg-gray-800">
                <div class="flex items-start justify-between">
                    <p class="text-[1rem] font-bold leading-4 text-blue-800 dark:text-gray-100">Product Sales</p>
                    <p class="text-xs leading-4 text-green-700 text-right">Up 2.3% <br /><span class="dark:text-gray400 text-gray-500">from last week</span></p>
                </div>
                <div class="pt-7">
                    <div class="flex items-center justify-between">
                        <a href="javascript:void(0)" class="focus:outline-none focus:underline focus:text-gray-600 hover:text-gray-600 text-gray-800 dark:text-gray-100"><p class="text-sm font-semibold leading-3 ">Apple MacBook Pro 2020</p></a>
                        <p class="text-sm font-semibold leading-none text-right text-gray-800 dark:text-gray-100">$2200</p>
                    </div>
                    <div class="flex items-center justify-between mt-2">
                        <p class="text-sm leading-3 text-blue-700">(ID 879-10-940)</p>
                        <div>
                            <div class="flex items-center justify-center px-2 py-1 w-full h-full bg-green-100 rounded-full">
                                <p class="text-xs leading-3 text-green-700">Shipped</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pt-5">
                    <div class="flex items-center justify-between">
                        <a href="javascript:void(0)" class="focus:outline-none focus:underline focus:text-gray-600 hover:text-gray-600 text-gray-800 dark:text-gray-100"><p class="text-sm font-semibold leading-3 ">MS Surface 2019</p></a>
                        <p class="text-sm font-semibold leading-none text-right text-gray-800 dark:text-gray-100">$2200</p>
                    </div>
                    <div class="flex items-center justify-between mt-2">
                        <p class="text-sm leading-3 text-blue-700">(ID 879-10-940)</p>
                        <div>
                            <div class="flex items-center justify-center px-2 py-1 w-full h-full bg-red-100 rounded-full">
                                <p class="text-xs leading-3 text-red-700">Cancelled</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pt-7">
                    <div class="flex items-center justify-between">
                        <a href="javascript:void(0)" class="focus:outline-none focus:underline focus:text-gray-600 hover:text-gray-600 text-gray-800 dark:text-gray-100"><p class="text-sm font-semibold leading-3 ">Iphone 12 Mini</p></a>
                        <p class="text-sm font-semibold leading-none text-right text-gray-800 dark:text-gray-100">$2200</p>
                    </div>
                    <div class="flex items-center justify-between mt-2">
                        <p class="text-sm leading-3 text-blue-700">(ID 879-10-940)</p>
                        <div>
                            <div class="flex items-center justify-center px-2 py-1 w-full h-full bg-green-100 rounded-full">
                                <p class="text-xs leading-3 text-green-700">Shipped</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pt-7">
                    <div class="flex items-center justify-between">
                        <a href="javascript:void(0)" class="focus:outline-none focus:underline focus:text-gray-600 hover:text-gray-600 text-gray-800 dark:text-gray-100"><p class="text-sm font-semibold leading-3 ">Google Pixel 5</p></a>
                        <p class="text-sm font-semibold leading-none text-right text-gray-800 dark:text-gray-100">$2200</p>
                    </div>
                    <div class="flex items-center justify-between mt-2">
                        <p class="text-sm leading-3 text-blue-700">(ID 879-10-940)</p>
                        <div>
                            <div class="flex items-center justify-center px-2 py-1 w-full h-full bg-yellow-100 rounded-full">
                                <p class="text-xs leading-3 text-yellow-700">Processing</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="pt-7">
                    <div class="flex items-center justify-between">
                        <a href="javascript:void(0)" class="focus:outline-none focus:underline focus:text-gray-600 hover:text-gray-600 text-gray-800 dark:text-gray-100"><p class="text-sm font-semibold leading-3 ">Apple MacBook Pro 2020</p></a>
                        <p class="text-sm font-semibold leading-none text-right text-gray-800 dark:text-gray-100">$2200</p>
                    </div>
                    <div class="flex items-center justify-between mt-2">
                        <p class="text-sm leading-3 text-blue-700">(ID 879-10-940)</p>
                        <div>
                            <div class="flex items-center justify-center px-2 py-1 w-full h-full bg-green-100 rounded-full">
                                <p class="text-xs leading-3 text-green-700">Shipped</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<?php
foreach ($this->list_menu as $v) {
?>
<h1><?= $v['name']; ?></h1>
<?php
}
?>