<?php
$me = $this;
?>
<div class="min-h-screen bg-bluegray-900">
  <div class="relative overflow-hidden">
    <header class="relative" x-data="{open:false}">
      <div class="bg-bluegray-900 pt-6">
        <nav class="relative max-w-7xl mx-auto flex items-center justify-between px-4 sm:px-6" aria-label="Global">
          <div class="flex items-center flex-1">
            <div class="flex items-center justify-between w-full md:w-auto">
              <a href="<?= $me->url("app");?>">
                <span class="sr-only"><?= $me->app_name; ?></span>
                <img class="h-8 w-auto sm:h-10 inline-block align-middle"
                  src="<?=$me->basePath("img/open_source.png");?>" alt="">
                <span
                  class="text-white font-extrabold inline-block text-2  xl align-middle"><?= $me->app_name; ?></span>
              </a>
              <div class="-mr-2 flex items-center md:hidden">
                <button @click="open = true" type="button"
                  class="bg-bluegray-900 rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:bg-bluegray-800 focus:outline-none focus:ring-2 focus-ring-inset focus:ring-white"
                  id="main-menu" aria-haspopup="true" x-bind:aria-expanded="open">
                  <span class="sr-only">Open main menu</span>
                  <!-- Heroicon name: menu -->
                  <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                    stroke="currentColor" aria-hidden="true">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  </svg>
                </button>
              </div>
            </div>
            <div class="hidden space-x-8 md:flex md:ml-10">
              <a href="#" class="text-base font-medium text-white hover:text-mygreen">About <b
                  class="text-mygreen"><?= $me->app_name; ?></a>
              <a href="<?= $me->url("app/term-condition");?>"
                class="text-base text-mygreen hover:text-mygreen font-extrabold">Terms and Conditions</a>
            </div>
          </div>
        </nav>
      </div>
      <div x-show="open" x-description="Mobile menu, show/hide based on menu open state."
        x-transition:enter="duration-150 ease-out" x-transition:enter-start="opacity-0 scale-95"
        x-transition:enter-end="opacity-100 scale-100" x-transition:leave="duration-100 ease-in"
        x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-95"
        class="absolute top-0 inset-x-0 p-2 transition transform origin-top md:hidden">
        <div class="rounded-lg shadow-md bg-white ring-1 ring-black ring-opacity-5 overflow-hidden">
          <div class="px-5 pt-4 flex items-center justify-between">
            <div>
              <a href="<?= $me->url("app");?>">
              <img class="h-8 w-auto inline-block align-middle" src="<?=$me->basePath("img/open_source.png");?>" alt="">
              <span
                class=" font-extrabold inline-block text-2xl align-middle text-mygreen"><?= $me->app_name; ?></span>
              </a>
            </div>
            <div class="-mr-2">
              <button @click="open = false" type="button"
                class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:bg-bluegray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-600">
                <span class="sr-only">Close menu</span>
                <!-- Heroicon name: x -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
                  stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
          <div class="pt-5 pb-6" role="menu" aria-orientation="vertical" aria-labelledby="main-menu">
            <div class="px-2 space-y-1" role="none">
              <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-900 hover:bg-mygreen-hover"
                role="menuitem">About <strong class="text-mygreen"><?= $me->app_name; ?></strong></a>

              <a href="<?= $me->url("app/term-condition");?>"
                class="block px-3 py-2 rounded-md text-base text-mygreen hover:bg-mygreen-hover font-extrabold"
                role="menuitem">Terms and Conditions</a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <main>
      <div class="bg-bluegray-900 text-white lg:overflow-hidden">
        <div class="mx-auto">
          <div class="lg:grid lg:grid-cols-1">
            <div class="mx-auto xs:max-w-sm sm:max-w-xl lg:max-w-5xl lg:text-left lg:flex lg:items-center">
              <div class="sm:py-8 lg:py-12">
                <div class="privacy-content-container">
                  <h1 class="text-5xl font-extrabold">Terms of Service</h1>
                  <h3 class="text-yellow-400">Updated Mei 19, 2020</h3>
                  <br>
                  <ol>
                    <li type="1" class="text-2xl"><strong>PENGERTIAN</strong>
                      <ul class="text-sm">
                        <li type='a'><strong>TELKOM</strong> adalah Badan Usaha Milik Negara yang dalam hal ini sebagai penyedia
                          layanan digital dan pemilik dari layanan aplikasi notadinas elektronik.</li>
                        <li type='a'><strong>Pengguna</strong> adalah setiap pihak yang membuka, menggunakan, atau mengakses situs
                          web ini.</li>
                        <li type='a'><strong>Undang-undang Hak Cipta</strong> adalah Undang-undang Nomor 28 tahun 2014 tentang Hak
                          Cipta.</li>
                        <li type='a'><strong>Situs </strong> adalah situs web yang beralamat di <a href="#"
                            class="text-red-400"><em>minitool.telkom.co.id</em></a>
                        </li>
                        <li type='a'><strong>Situs Pihak Ketiga</strong> adalah situs yang dioperasikan oleh pihak/perusahaan
                          lain.</li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>KETENTUAN PENGGUNAAN</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                          Ketentuan Penggunaan berlaku untuk Situs (<a href="#" class="text-red-400"><em>minitool.telkom.co.id</em></a>) yang dioperasikan oleh TELKOM dan setiap informasi yang terdapat dan/atau disalurkan melalui server TELKOM.
                          Pengguna yang engakses Situs ini dianggap telah membaca dan menyetujui ketentuan pengunaan Situs ini.
                        </li>
                        <li type="circle" class="mb-3">
                          TELKOM dapat sewaktu-waktu mengubah, menambah dan/atau menghapus bagian manapun dari Ketentuan
                          Penggunaan tanpa pemberitahuan terlebih dahulu.
                        </li>
                        <li type="circle" class="mb-3">
                          Pengguna disarankan membaca dengan seksama dan secara berkala mengunjungi halaman ini untuk
                          mendapatkan informasi terkini untuk mengetahui segala perubahan dalam ketentuan Penggunaan.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>PENGGUNAAN UMUM SITUS</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                          Pengguna menyatakan bahwa pengguna adalah benar pegawai Telkom dan atau Mitra yang berkerja di
                          bawah naungan Perusahaan Telkom dan dalam pengawasan Pegawai yang bertanggung jawab terhadap Mitra terebut.
                        </li>
                        <li type="circle" class="mb-3">
                          Segala hal terkait pengaksesan dan penggunaan Situs ini dilakukan atas tanggung jawab
                          Pengguna, sehingga semua risiko untuk penggunaan Situs ini ditanggung oleh Pengguna.
                        </li>
                        <li type="circle" class="mb-3">
                          TELKOM berhak meminta Pengguna untuk memberikan informasi yang akurat pada saat pendaftaran
                          akun agar dapat beberapa fitur atau layanan sesuai yang tertera dalam Kebijakan Privasi.
                        </li>
                        <li type="circle" class="mb-3">
                          TELKOM berhak menutup dan/atau memberhentikan akses terhadap Situs dan/atau memblokir akun
                          Pengguna dan/atau embatasi pengunaan layanan oleh Pengguna sewaktu-waktu tanpa diperlukannya pemberitahuan
                          apabila :
                          <ul class="pl-5">
                            <li type='a'>Pengguna telah melakukan pelanggaran terhadap larangan-larangan sebagaimana
                              yang tercantum dalam butir 5 Pemakaian Yang Dilarang.</li>
                            <li type='a'>Pengguna memberikan keterangan palsu, tidak benar, atau tidak lengkap terhadap
                              data dan informasi yang dibutuhkan termasuk identitas Pengguna.</li>
                            <li type='a'>Adanya permintaan dari aparat penegak hukum guna kepentingan penyidikan sesuai
                              dengan peraturan dan ketentuan hukum yang berlaku di Negara Republik Indonesia.</li>
                          </ul>
                        </li>
                        <li type="circle" class="mb-3">
                          Penggunaan Situs hanya untuk penggunaan kedinasan dan tidak bersifat pribadi.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>PEMBATASAN TANGGUNG JAWAB TELKOM</strong>
                      <ul class="text-sm">
                        Pengguna dilarang untuk:
                        <ul>
                          <li type='a'>Menggunakan Situs atau isinya untuk tujuan apapun yang melanggar hukum atau
                            dilarang oleh Ketentuan Penggunaan ini;</li>
                          <li type='a'>Mengambil, mengunduh, memungut atau menyimpan informasi pribadi tentang pengguna
                            lain;</li>
                          <li type='a'>Menggunakan program-program seperti robot, spider, scraper atau cara otomatis
                            atau manual lainnya untuk mengakses, memantau atau menyalin konten dan/atau informasi apapun di Situs;</li>
                          <li type='a'>Mengirim virus, spam, program atau teknik lainnya pada Situs;</li>
                          <li type='a'>MeMINITOOLkompilasi, membongkar, atau merekayasa balik setiap perangkat lunak
                            atau konten yang digunakan di bagian manapun dari Situs atau jaringan TELKOM;</li>
                          <li type='a'>Melakukan tindakan apapun untuk menghindar dari langkah-langkah yang dapat TELKOM
                            gunakan untuk mencegah, mengganggu, atau membatasi akses ke Situs atau jaringan TELKOM;</li>
                          <li type='a'>Membuat terjadinya Overload atau crash terhadap Situs, server atau jaringan
                            TELKOM; dan</li>
                          <li type='a'>Melakukan segala tindakan lainnya yang dapat menghambat dan/atau mempengaruhi
                            TELKOM untuk melakukan pengoperasian Situs, layanan, dan perangkat.</li>
                        </ul>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>HAK KEKAYAAN INTELEKTUAL</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                        Segala merk dagang, merk layanan, logo, gambar, ikon, produk dan nama jasa, desain dan nama
                        perusahaan serta yang terdapat dalam Situs, baik yang telah terdaftar maupun belum tidak terdaftar, merupakan
                        merk dagang milik TELKOM, anak perusahaan atau pihak ketiga lainnya yang tidak boleh disalin, ditiru, atau
                        digunakan, baik secara keseluruhan atau sebagian tanpa persetujuan tertulis dari TELKOM atau pemilik terkait sesuai dengan Undang-Undang Hak Cipta.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>KEAMANAN</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                        Pengguna mungkin akan memerlukan sebuah nama pengguna, nama akun, atau kata sandi untuk
                        mengakses beberapa bagian dari Situs. Penggunaan fitur-fitur ini merupakan tanda persetujuan dari Pengguna untuk
                        menjaga kerahasiaan dan keamanan informasi ini.
                        </li>
                        <li type="circle" class="mb-3">
                        Pengguna bertanggung jawab atas semua aktivitas yang terjadi dengan nama pengguna, akun atau
                        kata sandi. Jika kerahasiaan nama pengguna, akun atau kata sandi Pengguna digunakan oleh pihak lain, maka
                        Pengguna dengan segera harus memberi tahu TELKOM melalui <a href='mailto:abuse@telkom.co.id' class="font-extrabold text-red-400"><em>abuse@telkom.co.id</em></a> dan dengan Subyek email berupa <span class="font-extrabold">“Aduan Privasi”</span>.
                        </li>
                        <li type="circle" class="mb-3">
                        TELKOM tidak bertanggung jawab atas kerugian yang mungkin dialami oleh Pengguna akibat pihak
                        lain menggunakan akun atau kata sandi Pengguna.
                        </li>
                        <li type="circle" class="mb-3">
                        TELKOM berhak untuk menghentikan akun atau menangguhkan akun, serta mengubah nama pengguna atau
                        kata sandi, dan meminta informasi tambahan dari Pengguna serta melakukan tindakan wajar, perlu, dan penting
                        lainnya demi melindungi keamanan Situs dan akun Pelanggan.
                        </li>
                        <li type="circle" class="mb-3">
                        Pengguna dilarang mempublikasikan celah keamanan yang ditemukan dalam Situs atau layanan TELKOM
                        lainnya kepada khalayak umum tanpa seizin TEKOM.
                        </li>
                        <li type="circle" class="mb-3">
                        Pengguna dilarang memanfaatkan celah keamanan yang ditemukan dalam Situs atau Layanan TELKOM
                        lainnya untuk kepentingan pribadi atau kelompok tertentu.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>TANGGAPAN (FEEDBACK)</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                        Segala tanggapan, saran, dan atau penemuan yang anda berikan terkait Situs ini dan layanan
                        lainnya dianggap ebagai non confidential. TELKOM berhak atas pengunaan informasi ini secara bebas tanpa batas.
                        Pelanggan dilarang untuk menyalahgunakan penemuan dari Situs yang dapat mempengaruhi TELKOM dalam
                        melakukan pengoperasian Situs dan layanan lainnya.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>PERATURAN YANG BERLAKU</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                        Ketentuan Penggunaan ini diatur oleh dan akan diberlakukan berdasarkan peraturan
                        perundang-undangan yang berlaku di Republik Indonesia.
                        </li>
                      </ul>
                    </li>
                    <br>
                    <li type="1" class="text-2xl"><strong>KEBIJAKAN PRIVASI</strong>
                      <ul class="text-sm">
                        <li type="circle" class="mb-3">
                        Kebijakan privasi aplikasi berikut ini menjelaskan bagaimana Kami mengumpulkan, menggunakan,
                        memindahkan, mengungkapkan dan melindungi informasi pribadi Anda yang dapat diidentifikasi yang diperoleh
                        melalui Situs Kami (sebagaimana didefinisikan di bawah). Mohon Anda membaca Kebijakan Privasi ini dengan seksama
                        untuk memastikan bahwa Anda memahami bagaimana ketentuan Kebijakan Privasi ini Kami berlakukan.
                        </li>
                        <li type="circle" class="mb-3">
                        Kebijakan Privasi ini disertakan sebagai bagian dari Ketentuan Penggunaan Kami. Kebijakan
                        Privasi ini mencakup hal-hal sebagai berikut:
                        <ol class="pl-5">
                          <li type="a" class="font-bold">Definisi</li>
                          <li type="a" class="font-bold">Informasi yang Kami kumpulkan</li>
                          <li type="a" class="font-bold">Keamanan</li>
                          <li type="a" class="font-bold">Perubahan atas Kebijakan Privasi ini</li>
                          <li type="a" class="font-bold">Pengakuan dan persetujuan</li>
                          <li type="a" class="font-bold">Cara untuk menghubungi Kami</li>
                        </ol>
                        <br>
                        Penggunaan Anda atas Situs dan Layanan Kami tunduk pada Ketentuan Penggunaan dan Kebijakan
                        Privasi ini dan mengindikasikan persetujuan Anda terhadap Ketentuan Penggunaan dan Kebijakan Privasi
                        tersebut.
                        <ul class="mt-5">
                          <li class="font-bold">Definisi</li>
                            <ul class="pl-5">
                              <li type='circle'><strong>"Kami"</strong> berarti Perusahaan Perseroan (Persero) PT. Telekomunikasi Indonesia,
                                Tbk., suatu perusahaan ya class="pl-5"ng didirikan berdasarkan hukum Negara Republik Indonesia.</li>
                              <li type='circle'><strong>"Layanan"</strong> berarti seluruh layanan yang terdapat pada situs <a href="#" class="text-red-400"><em>minitool.telkom.co.id</em></a></li>
                              <li type='circle'><strong>"Informasi Pribadi"</strong> berarti informasi mengenai Anda yang secara pribadi dapat
                                diidentifikasi yang dikumpulkan melalui Aplikasi, seperti nama, alamat, tanggal lahir, nomor telepon,
                                lokasi bekerja, alamat surat elektronik (e-mail) Anda dan/atau sejenisnya, dan informasi lain yang
                                berkaitan dengan Human Capital.</li>
                              <li type='circle'><strong>"Situs"</strong> berarti Situs Web Kami di <a href="#" class="text-red-400"><em>minitool.telkom.co.id</em></a></li>
                            </ul>
                            <br>
                            <li class="font-bold">Informasi yang Kami Kumpulkan</li>
                            <ul class="pl-5">
                              <li type='circle'>Kami mengumpulkan Informasi Pribadi tertentu dari berupa Nama, NIK, Jabatan,
                                Divisi dan Lokasi kerja untuk memberikan layanan yang sesuai dengan kebutuhan anda.</li>
                              <li type='circle'>Ketika Anda mengunjungi Situs Web Kami, administrator Situs Web Kami akan
                                memproses data teknis seperti alamat IP Anda, browser internet yang Anda gunakan, dan durasi setiap
                                kunjungan/sesi yang memungkinkan Kami untuk mengirimkan fungsi-fungsi Situs Web.</li>
                            </ul>
                            <br>
                            <li class="font-bold">Keamanan</li>
                            <ul class="pl-5">
                              <li type='circle'>
                            Kami akan menjaga kerahasiaan setiap data yang diberikan oleh Anda. Namun, Kami tidak
                            menjamin keamanan database Kami dan Kami juga tidak menjamin bahwa data yang Anda berikan tidak akan
                            tertahan/terganggu ketika sedang dikirimkan kepada Kami. Anda tidak diperbolehkan mengungkapkan sandi Anda kepada siapapun. Bagaimanapun efektifnya suatu teknologi, tidak ada sistem keamanan yang tidak dapat
                            ditembus.</li>
                            </ul>
                            <br>
                            <li class="font-bold">Perubahan atas Kebijakan Privasi ini</li>
                            <ul class="pl-5">
                              <li type='circle'>
                            Kami dapat mengubah Kebijakan Privasi ini untuk mencerminkan perubahan dalam kegiatan Kami.
                            Kami menghimbau Anda untuk meninjau halaman ini secara berkala untuk mengetahui informasi terbaru tentang
                            bagaimana ketentuan Kebijakan Privasi ini Kami berlakukan.</li>
                            </ul>
                            <br>
                            <li class="font-bold">Lain-lain</li>
                            <ul class="pl-5">
                              <li type='circle'>
                            Hukum yang mengatur dan yurisdiksi. Kebijakan Privasi ini diatur oleh dan untuk ditafsirkan
                            dalam hukum Negara Republik Indonesia. Setiap dan seluruh sengketa yang timbul dari kebijakan privasi
                            ini akan diatur oleh yurisdiksi eksklusif dari Pengadilan Negeri Jakarta Selatan.</li>
                            </ul>
                            <br>
                            <li class="font-bold">Pengakuan dan Persetujuan</li>
                            <ul class="pl-5">
                              <li type='circle'>
                                Dengan menggunakan Aplikasi, Anda mengakui bahwa Anda telah membaca dan
                                memahami Kebijakan Privasi ini dan Ketentuan Penggunaan dan setuju dan sepakat terhadap penggunaan,
                                praktek, pemrosesan dan pengalihan informasi pribadi Anda oleh Kami sebagaimana dinyatakan di dalam Kebijakan Privasi ini</li>
                              <li type='circle'>Anda juga menyatakan bahwa Anda memiliki hak untuk membagikan seluruh
                                informasi yang telah Anda berikan kepada Kami dan untuk memberikan hak kepada Kami untuk menggunakan dan
                                membagikan informasi tersebut kepada Penyedia Layanan</li>
                            </ul>
                            <br>
                            <li class="font-bold">Cara untuk menghubungi Kami</li>
                            <ul class="pl-5">
                              <li type='circle'>
                            Hukum yang mengatur dan yurisdiksi. Kebijakan Privasi ini diatur oleh dan untuk ditafsirkan
                            dalam hukum Negara Republik Indonesia. Setiap dan seluruh sengketa yang timbul dari kebijakan privasi
                            ini akan diatur oleh yurisdiksi eksklusif dari Pengadilan Negeri Jakarta Selatan.</li>
                              <li type='circle'><strong>Helpdesk IT</strong> : (Telegram) <strong>0811 2244 472</strong>, (Phone) <strong>1500472</strong>, (Email) <a
                              href="mailto:it-care@telkom.co.id" class="text-red-400 font-bold"><em>it-care@telkom.co.id</em></a></li>
                            </ul>
                          </ul>
                        </ul>
                        </li>
                      </ul>
                    </li>
                  </ol>

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- More main page content here... -->
    </main>
  </div>
</div>