<?php
    $me = $this;
    $ini_reader = new \Laminas\Config\Reader\Ini();
    $conf = $ini_reader->fromFile(conf_path() . env('APPLICATION_ENV') . ".conf");
    $app_conf = $conf['app-config'];
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title><?= strtoupper($app_conf['app_name']); ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?=$me->basePath("js-lib/bootstrap/dist/css/bootstrap.min.css");?>" rel="stylesheet">
    <meta name="theme-color" content="#563d7c">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="<?=$me->basePath("/vendor/login-1/css/floating-labels.css");?>" rel="stylesheet">
</head>

<body onload="loadBody()">
    <div>
        <?php
// \Zend\Debug\Debug::dump($me->msg);
// \Zend\Debug\Debug::dump($me->wait);
// \Zend\Debug\Debug::dump($me->try);
// \Zend\Debug\Debug::dump($me->isLoginError);
// \Zend\Debug\Debug::dump($me->redirectUrl);
?>
    </div>
    <?php
if ($me->wait > 0) {
    ?>
    <script>let wait = <?=$me->wait;?>;</script>
    <div class="w-75 m-auto  text-center d-block">
        <a class="btn btn-dark text-center text-white font-weight-bold px-5" href="<?=$me->url("app");?>"><h1 class=""><?= strtoupper($app_conf['app_name']); ?></h1></a>
        <p class="mt-2 text-center">by <strong><?= $app_conf['copy_owner']; ?></strong></p>
        <div class="alert alert-danger text-center m-auto" role="alert">
            <h4 class="alert-heading">Please wait for <span id="spanSecond"><?=$me->wait;?></span> s</h4>
            <hr>
            <p class="mb-0">
            You have been input invalid data more than <?=_MAX_LOGIN_TRY_;?> times<br>
            <a class="btn btn-sm" href="<?=$me->url("app/auth/login");?>"><small><strong>REFRESH PAGE</strong></small></a>
            </p>
        </div>
    </div>
    <?php
} else {
    ?>
    <form onsubmit="submitForm()" class="form-signin" method="post" action="<?=$me->url("app/auth/login", [], ['query' => ($me->redirectUrl !== null && $me->redirectUrl !== "") ? ['redirectUrl' => $me->redirectUrl] : []]);?>">
        <div class="text-center mb-4">
            <a class="btn btn-dark text-white font-weight-bold px-5" href="<?=$me->url("app");?>"><h1 class=""><?= strtoupper($app_conf['app_name']); ?></h1></a>
            <p class="mt-2">by <strong><?= $app_conf['copy_owner']; ?></strong></p>
            <?php
if ($me->msg !== "" && $me->isLoginError) {
        ?>
                <div class="alert alert-warning" role="alert" id="alert2">
                    <?=$me->msg;?>
                </div>
            <?php
}
    ?>
            <div class="alert alert-dark d-none" role="alert" id="alert1">
                <div class="spinner-border mx-2 d-inline-block align-middle" id="spinner1" role="status"></div>
                <h6 class="alert-heading d-inline align-middle" id="title1">PLEASE WAIT...</h6>
            </div>
        </div>

        <div class="form-label-group mt-5">
            <input type="username" name="username" id="inpUsername" class="form-control"
            placeholder="Username" required="" autofocus="">
            <label for="inpUsername">Username</label>
        </div>

        <div class="form-label-group">
            <input type="password" name="password" id="inputPassword" class="form-control"
            placeholder="Password" required=""  AUTOCOMPLETE="off">
            <label for="inputPassword">Password</label>
        </div>

        <div class="custom-control custom-checkbox mt-3 mb-4 mr-sm-2">
            <input type="checkbox" value="on" name="remember_me" class="custom-control-input" id="inpRememberMe">
            <label class="custom-control-label" for="inpRememberMe">Remember Me</label>
        </div>
        <?=$me->formElement($form->get('redirect_url'));?>
        <?=$me->formElement($form->get('csrf'))?>

        <button class="btn btn-lg btn-danger btn-block" type="submit" id="inpSubmit" name="submit">Sign in</button>
        <p class="mt-5 mb-3 text-muted text-center">&copy; <?= $app_conf['copy_year']; ?><?= ((int) date("Y") > (int)$app_conf['copy_year']) ? "-" . date("Y") : "";?></p>
    </form>
    <?php
}
?>

    <script>
        let spanSecond;
        function submitForm(){
            let el1 = document.getElementById("alert1");
            el1.classList.remove("d-none");
            let el2 = document.getElementById("alert2");
            if(el2!==null && el2!==undefined){
                el2.classList.add("d-none");
            }
        }

        function loadBody(){
            spanSecond = document.getElementById("spanSecond");
            if(spanSecond!==null && spanSecond!==undefined){
                setInterval(() => {
                    // console.log(wait);
                    spanSecond.innerText = wait;
                    wait--;

                    if(wait<=0){
                        location.replace("<?=$me->url("app/auth/login", [], ['query' => ($me->redirectUrl !== null && $me->redirectUrl !== "") ? ['redirectUrl' => $me->redirectUrl] : []]);?>");
                    }
                }, 1000);
            }
        }
    </script>
</body>

</html>