<?php
    $me = $this;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?=$me->headTitle()->setAutoEscape(false)?>

    <?=$me->headMeta()
->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no')
->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
->appendHttpEquiv('Content-Security-Policy',
    "script-src 'self' 'unsafe-inline';
        style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
        connect-src 'self';
        font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com;
        child-src 'self';
        img-src 'self' data:;
        media-src 'self';
        object-src 'self';")
?>
    <?=$me->headLink([
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $me->basePath() . '/img/favicon.ico']);
?>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?=$me->basePath("bower_components/fontawesome/css/all.min.css");?>">
    <!-- Ionicons -->
    <link rel="stylesheet" href="<?=$me->basePath("bower_components/ionicons/docs/css/ionicons.min.css");?>">
    <!-- Theme style -->
    <link rel="stylesheet" href="<?=$me->basePath("vendor/admin_lte/dist/css/adminlte.min.css");?>">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <style>
        .lockscreen{
            background-color: #93c0ec;
        }

        .lockscreen-image{
            width:120px;
            height:120px;
            left:-45px;
            border: 5px solid white;
            cursor: pointer;
        }
        .lockscreen-image:hover{
            border: 5px solid #6495ED;
        }
        .lockscreen-image div{
            padding: 0;
            font-size: 85px;
            text-align: center;
            margin-top: -12px;
        }
        .lockscreen-image div:hover {
            color: #ADD8E6 !important;
        }
    </style>
</head>
<?php
$content = $me->content;
$vars = $me->vars();
//!d($vars);
?>
<body class="hold-transition lockscreen" onload="loadBody()">
<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
    <div class="lockscreen-logo">
        <a href="<?=$me->url(strtolower($vars['module']));?>">Dashboard <strong class="text-navy"><?=$vars['module'];?></strong></a>
    </div>
    <!-- User name -->
    <div class="lockscreen-name"></div>

    <?php
if ($me->wait > 0) {
    ?>
        <script>let wait = <?=$me->wait;?>;</script>
        <div class="w-100 m-auto  text-center d-block">
            <div class="help-block alert alert-danger text-center m-auto" role="alert">
                <h4 class="alert-heading">Please wait for <span id="spanSecond"><?=$me->wait;?></span> s</h4>
                <hr>
                <p class="mb-0">
                You have been input invalid data more than <?=_MAX_LOGIN_TRY_;?> times<br>
                <a class="btn btn-sm" href="<?=$me->url(strtolower($vars['module']) . "/auth/login");?>"><small><strong>REFRESH PAGE</strong></small></a>
                </p>
            </div>
        </div>
    <?php
} else {
    ?>
        <!-- START LOCK SCREEN ITEM -->
        <div class="lockscreen-item">
            <!-- lockscreen image -->
            <div class="lockscreen-image bg-navy" onclick="submitSigninForm();">
                <div class="text-white"><em class="fa fa-power-off"></em></div>
            </div>
            <!-- /.lockscreen-image -->

            <!-- lockscreen credentials (contains the form) -->
            <form class="lockscreen-credentials" id="form-signin" method="post" action="<?=$me->url(strtolower($vars['module']) . "/auth/login");?>">
                <input type="hidden" name="module_name" value="<?=$vars['module'];?>"/>
                <input type="hidden" value="on" name="remember_me" class="custom-control-input" id="inpRememberMe"/>
                <div class="input-group border-bottom">
                    <input type="text" class="form-control" placeholder="username" name="username" id="inpUsername">

                    <div class="input-group-append">
                        <div class="mt-2 mx-2"><em class="fas fa-user text-navy"></em></div>
                    </div>
                </div>
                <div class="input-group border-top">
                    <input type="password" class="form-control" placeholder="password" name="password" id="inputPassword"  AUTOCOMPLETE="off">

                    <div class="input-group-append">
                        <div class="mt-2 mx-2"><em class="fas fa-key text-navy"></em></div>
                    </div>
                </div>

                <?=$me->formElement($form->get('redirect_url'));?>
                <?=$me->formElement($form->get('csrf'))?>
            </form>
            <!-- /.lockscreen credentials -->

        </div>
        <!-- /.lockscreen-item -->
    <?php
}
?>

    <?php
if ($me->msg !== "" && $me->isLoginError) {
    ?>
        <div class="help-block text-center alert alert-warning p-2" role="alert" id="alert2">
            <?=$me->msg;?>
        </div>
    <?php
}
?>
    <div class="help-block text-center alert alert-info p-2 d-none" role="alert" id="alert1">
        <div class="spinner-border mx-2 d-inline-block align-middle" id="spinner1" role="status"></div>
        <h6 class="alert-heading d-inline align-middle" id="title1">PLEASE WAIT...</h6>
    </div>

    <div class="lockscreen-footer text-center mt-5 pt-5">
        <strong>PT Telekomunikasi Indonesia</strong> &copy; 2020<?=((int) date("Y") > 2020) ? "-" . date("Y") : "";?><br>
        All rights reserved
    </div>
</div>
<!-- /.center -->

<!-- jQuery -->
<script src="<?=$me->basePath("bower_components/jquery/dist/jquery.min.js");?>"></script>
<script src="<?=$me->basePath("bower_components/jquery-migrate/jquery-migrate.min.js");?>"></script>
<!-- Bootstrap 4 -->
<script src="<?=$me->basePath("bower_components/bootstrap4/dist/js/bootstrap.bundle.min.js");?>"></script>
<script>
let signinForm,spanSecond;
$(document).ready(function(){
    signinForm = $("#form-signin");
    signinForm.find('input').on('keyup',function(e){
        // console.log(e);
        if(e.code==="Enter")submitSigninForm();
    });
});

function submitSigninForm(){
    let el1 = document.getElementById("alert1");
    el1.classList.remove("d-none");
    let el2 = document.getElementById("alert2");
    if(el2!==null && el2!==undefined){
        el2.classList.add("d-none");
    }
    signinForm.submit();
}


function loadBody(){
    spanSecond = document.getElementById("spanSecond");
    if(spanSecond!==null && spanSecond!==undefined){
        setInterval(() => {
            // console.log(wait);
            spanSecond.innerText = wait;
            wait--;

            if(wait<=0){
                location.replace("<?=$me->url(strtolower($vars['module']) . "/auth/login", [], ['query' => ($me->redirectUrl !== null && $me->redirectUrl !== "") ? ['redirectUrl' => $me->redirectUrl] : []]);?>");
            }
        }, 1000);
    }
}
</script>
</body>
</html>