<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
$me = $this;
// !d($me);
$headScript = $me->headScript();
$headScript->captureStart();
?>
var _is_login_error = "<?= $me->is_login_error;?>";
var _msg = "<?= $me->msg;?>";
var _wait = <?= $me->wait_time;?>;
<?php
$headScript->captureEnd();
?>
<!-- blank layout -->
<?=$me->doctype()?>
<?php
$content = $me->content;
// zdebug($content);die();
// !d(get_class_methods($me));//die();
$vars = $me->vars();
// !d($vars);die();
$_vars = $vars['_vars_']??[];
$module = $_vars['module']??"";
$controller = $_vars['controller']??"";
$controller = str_replace("Controller", "", $controller);
$action = $_vars['action']??"";
$layout = $_vars['layout']??"";
// !d($layout);die();
$active_menu = $me->active_menu??"";
if(isset($vars['content'])){
  unset($vars['content']);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <?=$me->headMeta()?>
    <?=$me->headTitle()->setAutoEscape(false)?>
    <?=$me->headLink(['rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $me->basePath() . '/img/open_source.png']);?>
    <script src="/js-lib/alpine-js/spruce.umd.js"></script>
    <script src="/js-lib/alpine-js/alpine.min.js" defer></script>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,600,700&display=swap" rel="stylesheet">
    <link href="<?=$me->basePath("vendor/cork/bootstrap/css/bootstrap.min.css"); ?>" rel="stylesheet" type="text/css" />
    <link href="<?=$me->basePath("vendor/cork/assets/css/plugins.css"); ?>" rel="stylesheet" type="text/css" />
    <link href="<?=$me->basePath("vendor/cork/assets/css/authentication/form-2.css"); ?>" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="<?=$this->basePath("font/inter/inter.css");?>">
    <link rel="stylesheet" href="<?=$this->basePath(css_url()."vendor/".(env("APPLICATION_ENV","development")==="production"?"tailwind.min":"tailwind").".css");?>">
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="<?=$me->basePath("vendor/cork/assets/css/forms/theme-checkbox-radio.css"); ?>">
    <link rel="stylesheet" type="text/css" href="<?=$me->basePath("vendor/cork/assets/css/forms/switches.css"); ?>">
    <link rel="stylesheet" href="<?=$this->basePath("css-lib/spinner/spinner.css");?>">
    <link rel="stylesheet" href="<?=$this->basePath("css-lib/animate/animate.min.min.css");?>">

    <?=$me->partial('partial-css.phtml', ['_vars' => $_vars,'_module'=>$module,'_controller'=>$controller,'_action'=>$action,'_layout'=>$layout,'_active_menu'=>$active_menu]);?>

    <?=$me->headStyle()?>
</head>
<body class="form relative" x-data>
    <div class="form-container outer">
        <div class="form-form">
            <div class="form-form-wrap">
                <div class="form-container">
                    <div class="form-content">

                        <h1 class="">LAMIRA</h1>
                        <p class="">Log in to your account to continue.</p>

                        <form class="text-left" method="post">
                            <div class="form">

                                <div id="username-field" class="field-wrapper input">
                                    <label for="username">USERNAME</label>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                    <input x-cloak x-on:blur="$store.login_form.readonly.username = true" x-on:focus="$store.login_form.readonly.username = false" x-on:click="$store.login_form.readonly.username = false" x-model="$store.login_form.value.username" id="username" name="username" type="text" class="form-control readonly" placeholder="Username" autocomplete="off" x-bind:readonly="$store.login_form.readonly.username">
                                    <span x-show="$store.msg.form.username!=''" x-html="$store.msg.form.username" class="text-right w-100 d-block text-danger"></span>
                                </div>

                                <div id="password-field" class="field-wrapper input mb-2">
                                    <div class="d-flex justify-content-between">
                                        <label for="password">PASSWORD</label>
                                    </div>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
                                    <input x-on:blur="$store.login_form.readonly.password = true" x-on:focus="$store.login_form.readonly.password = false" x-on:click="$store.login_form.readonly.password = false" x-model="$store.login_form.value.password" id="password" name="password" type="password" class="form-control readonly" placeholder="Password" autocomplete="off" x-bind:readonly="$store.login_form.readonly.password">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" id="toggle-password" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                                    <span x-show="$store.msg.form.password!=''"  x-html="$store.msg.form.password" class="text-right w-100 d-block text-danger"></span>
                                </div>
                                <div class="d-sm-flex justify-content-between">
                                    <div class="field-wrapper">
                                        <button x-bind:disabled="$store.state.wait>0" type="submit" class="btn btn-danger" value="">Log In</button>
                                    </div>
                                </div>
                                <div class="d-sm-flex justify-content-center mt-3" x-show="$store.msg.info!=''">
                                  <span class="badge badge-primary" x-html="$store.msg.info"></span>
                                </div>

                                <p class="signup-link">Apabila ada <span class="font-extrabold">kendala dalam proses login atau kendala fungsi aplikasi</span> harap menghubungi kami melalui Telegram Group <a href="https://t.me/KawalISM" class="font-extrabold text-lightblue-500">KawalISM</a>.
                              </p>

                            </div>

                            <?=$me->formElement($form->get('redirect_url'));?>
                            <?=$me->formElement($form->get('csrf'))?>
                            <input type="hidden" name="meta_csrf_name" x-model="$store.login_form.value.meta_csrf_name">
                            <input type="hidden" name="meta_csrf_value" x-model="$store.login_form.value.meta_csrf_value">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div x-show="$store.loader.main" class="loader top-0 w-full h-full absolute text-center mx-auto bg-bluegray-800 opacity-70">
        <div class="ball-grid-pulse text-center absolute left-1/2 top-1/2 mt-[-30px] ml-[-30px]">
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <div class="bg-mygreen"></div>
            <span class=" text-white text-lg ml-[-25px]">processing....</span>
        </div>
    </div>

    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="<?=$me->basePath("vendor/cork/bootstrap/js/popper.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/lodash/lodash.min.js");?>"></script>
    <script src="<?=$me->basePath("js-lib/validate/validate.min.js");?>"></script>

    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="<?=$me->basePath("vendor/cork/assets/js/authentication/form-2.js");?>"></script>
    <script src="<?=$me->basePath("js/him/validate.js");?>"></script>

    <?=$me->headScript();?>

    <?=$me->partial('partial-js.phtml', ['_vars' => $_vars,'_module'=>$module,'_controller'=>$controller,'_action'=>$action,'_layout'=>$layout,'_active_menu'=>$active_menu]);?>
    <?=$me->inlineScript()?>

</body>
</html>