<?php
$me = $this;
$vars = $me->_vars;
// zdebug($vars);
$breadcrumb = $vars['breadcrumb']??[];
$rParam = $vars['route_param'];
// zdebug($breadcrumb);

if(count($breadcrumb)>0 || (($rParam['show_title']??false) && ($rParam['title']??"")!=="")){
?>
<nav class="bg-white border-b border-t border-bluegray-400 flex justify-between" aria-label="Breadcrumb">
  <ol class="flex-grow mx-auto px-4 hidden md:flex space-x-4 sm:px-1 lg:px-3">
    <?php
      $idx = 1;
      foreach($breadcrumb as $k=>$v){
        if($idx===1 && $idx!=count($breadcrumb)){
    ?>
    <li class="hidden lg:flex">
      <div class="flex items-center">
        <a href="<?= $v; ?>" class="ml-4 text-sm font-medium text-bluegray-500 hover:text-bluegray-900"><?= $k;?></a>
      </div>
    </li>
    <?php
        }else if($idx<count($breadcrumb)){
    ?>
    <li class="hidden lg:flex">
      <div class="flex items-center">
        <svg class="flex-shrink-0 w-3 h-full text-bluegray-500" viewBox="0 0 24 44" preserveAspectRatio="none"
          fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path d="M.293 0l22 22-22 22h1.414l22-22-22-22H.293z"></path>
        </svg>
        <a href="<?= $v;?>" aria-current="page" class="ml-4 text-sm font-medium text-bluegray-500 hover:text-bluegray-900"><?= $k;?></a>
      </div>
    </li>
    <?php
        }else{
    ?>
    <li class="flex">
      <div class="flex items-center">
        <svg class="flex-shrink-0 w-3 h-full text-bluegray-500" viewBox="0 0 24 44" preserveAspectRatio="none"
          fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
          <path d="M.293 0l22 22-22 22h1.414l22-22-22-22H.293z"></path>
        </svg>
        <a href="<?= $v;?>" aria-current="page" class="ml-2 text-sm font-extrabold text-bluegray-900"><?= $k;?></a>
      </div>
    </li>
    <?php
        }
        $idx++;
      }
    ?>
  </ol>
  <ol class="mx-auto px-4 flex space-x-4 sm:px-1 lg:px-3 h-9">
    <li class="flex">
      <div class="flex items-center font-extrabold">
        <?php
          if(($rParam['show_title']??false)){
            echo ($rParam['title']??"");
          }
        ?>
      </div>
    </li>
  </ol>
</nav>
<?php
}
?>