<?php
define("HTTP_INTERNALSERVERERROR", 500);
define("HTTP_REQUESTTIMEOUT", 404);
define("HTTP_NOTFOUND", 404);
define("HTTP_FORBIDDEN", 403);
define("HTTP_UNAUTHORIZED", 401);
define("HTTP_BADREQUEST", 400);
