<?php
$me       = $this;
$headLink = $me->headLink();
$headLink->appendStylesheet($me->basePath("js-lib/tom-select/tom-select.default.min.css"));
$headScript = $me->headScript();
$headScript->appendFile($me->basePath("js-lib/validate/validate.min.js"));
$headScript->appendFile($me->basePath("js/him/validate.js"));
$headScript->appendFile($me->basePath("js-lib/lodash/lodash.js"));
$headScript->appendFile($me->basePath("js-lib/tom-select/tom-select.complete.js"));
$headScript->appendFile($me->basePath("js-lib/xlsx/shim.min.js"));
$headScript->appendFile($me->basePath("js-lib/xlsx/xlsx.full.min.js"));
?>
<div x-data="{}">
  <div class="mx-auto bg-white dark:bg-gray-800 shadow rounded">
    <!-- DIV TOP RIGHT -->
    <div class="flex w-full pl-3 sm:pl-6 pr-3 py-5 items-center justify-between bg-indigo-100 rounded-t">
      <h3 class="text-gray-800 font-bold text-base sm:text-xl">List User</h3>
      <div class="flex gap-x-2 items-center">
        <button
          @click="$dispatch('show-create', {})"
          class="ml-0 bg-green-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 hover:bg-indigo-600 rounded text-white px-5 h-8 flex items-center text-sm">Create
          New</button>
        <button
          onclick="filterData(0, false)"
          class="ml-0 bg-blue-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 hover:bg-indigo-600 rounded text-white px-5 h-8 flex items-center text-sm">Reload
          Data</button>
      </div>
    </div>
    <!-- DIV TOP LEFT -->
    <div class="flex flex-col md:flex-row p-3 justify-between items-start md:items-stretch w-full">
      <div class="w-full flex flex-col md:flex-row items-start md:items-center justify-between">
        <div class="flex gap-x-2 items-center">
          <button
            @click="$dispatch('remove-all-user', {})"
            class="hover:text-white hover:bg-red-700 focus:ring-2 focus:ring-offset-2 focus:ring-red-700 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Delete table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon cursor-pointer icon-tabler icon-tabler-trash" width="20"
              height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" />
              <line x1="4" y1="7" x2="20" y2="7" />
              <line x1="10" y1="11" x2="10" y2="17" />
              <line x1="14" y1="11" x2="14" y2="17" />
              <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
              <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
            </svg>
          </button>
          <button
            @click="$dispatch('show-filter', {})"
            class="inline hover:text-white hover:bg-indigo-700 focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Filter table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="inline icon icon-tabler icon-tabler-adjustments" width="20"
              height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <circle cx="6" cy="10" r="2" />
              <line x1="6" y1="4" x2="6" y2="8" />
              <line x1="6" y1="12" x2="6" y2="20" />
              <circle cx="12" cy="16" r="2" />
              <line x1="12" y1="4" x2="12" y2="14" />
              <line x1="12" y1="18" x2="12" y2="20" />
              <circle cx="18" cy="7" r="2" />
              <line x1="18" y1="4" x2="18" y2="5" />
              <line x1="18" y1="9" x2="18" y2="20" />
            </svg>
            <span class="inline ">Filter</span>
          </button>
          <!-- <button
            class="hover:text-white hover:bg-indigo-700 focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Filter table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-sort" width="20"
              height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M3 9l4 -4l4 4m-4 -4v14"></path>
              <path d="M21 15l-4 4l-4 -4m4 4v-14"></path>
            </svg>
          </button> -->
        </div>
        <div class="flex gap-x-2 items-center">
          <button
            @click="$dispatch('show-upload', {})"
            class="inline hover:text-white hover:bg-sky-600 focus:ring-2 focus:ring-offset-2 focus:ring-sky-600 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Delete table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="inline icon cursor-pointer icon-tabler icon-tabler-upload" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2"></path>
              <polyline points="7 9 12 4 17 9"></polyline>
              <line x1="12" y1="4" x2="12" y2="16"></line>
            </svg>
            <span class="inline ">Upload</span>
          </button>
          <button
            @click="$dispatch('download-data', {})"
            class="inline hover:text-white hover:bg-amber-600 focus:ring-2 focus:ring-offset-2 focus:ring-amber-600 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Filter table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="inline icon icon-tabler icon-tabler-download" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2"></path>
              <polyline points="7 11 12 16 17 11"></polyline>
              <line x1="12" y1="4" x2="12" y2="16"></line>
            </svg>
            <span class="inline ">Download</span>
          </button>
          <!-- <button
            class="hover:text-white hover:bg-indigo-700 focus:ring-2 focus:ring-offset-2 focus:ring-indigo-700 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
            aria-label="Filter table" role="button">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrows-sort" width="20"
              height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
              stroke-linecap="round" stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
              <path d="M3 9l4 -4l4 4m-4 -4v14"></path>
              <path d="M21 15l-4 4l-4 -4m4 4v-14"></path>
            </svg>
          </button> -->
        </div>
      </div>
    </div>
    <!-- TABLE -->
    <div x-data="table" class="w-full pb-2 scrollbar-thin scrollbar-thumb-bluegray-700 scrollbar-track-bluegray-300 overflow-x-scroll">
      <table class="min-w-full bg-white dark:bg-gray-800 rounded border border-gray-300" aria-label="main table">
        <thead>
          <tr class="w-full bg-gray-100 dark:bg-gray-700 border-b border-gray-300">
            <th role="columnheader" class="pl-3 w-24 py-3">
              <div class="flex items-center">
                <input x-bind="bind.check_all" placeholder="check box" type="checkbox"
                  class="cursor-pointer relative w-5 h-5 border rounded border-gray-400 bg-white" />
                <div class="opacity-0 cursor-defaut ml-4 text-gray-800 dark:text-gray-100">
                  <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                    height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                    stroke-linecap="round" stroke-linejoin="round">
                    <path stroke="none" d="M0 0h24v24H0z" />
                    <polyline points="6 15 12 9 18 15" />
                  </svg>
                </div>
              </div>
            </th>
            <th role="columnheader" x-bind="bind.col_header" data-field="id" class="whitespace-nowrap pl-4 w-20 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative chuss-div">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  ID</p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.id.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.id.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.id.priority!==null" x-text="sorting.id.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="username"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  USERNAME
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.username.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.username.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.username.priority!==null" x-text="sorting.username.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="full_name"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  FULL NAME
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.full_name.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.full_name.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.full_name.priority!==null" x-text="sorting.full_name.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="email"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  EMAIL
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.email.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.email.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.email.priority!==null" x-text="sorting.email.priority"></span>
              </div>
            </th>
            <th role="columnheader" x-bind="bind.col_header" data-field="status"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-20 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  STATUS
                </p>
                <button role="button" aria-label="option" class="mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.status.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.status.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.status.priority!==null" x-text="sorting.status.priority"></span>
              </div>
            </th>
            <th role="columnheader" x-bind="bind.col_header" data-field="is_organic"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-20 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  IS ORGANIC
                </p>
                <button role="button" aria-label="option" class="mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.is_organic.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.is_organic.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.is_organic.priority!==null" x-text="sorting.is_organic.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="mobile_no"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  MOBILE NO
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.mobile_no.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.mobile_no.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.mobile_no.priority!==null" x-text="sorting.mobile_no.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="employ_nik"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  NIK
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.employ_nik.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.employ_nik.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.employ_nik.priority!==null" x-text="sorting.employ_nik.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="spv_nik"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  SPV
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.spv_nik.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.spv_nik.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.spv_nik.priority!==null" x-text="sorting.spv_nik.priority"></span>
              </div>
            </th>
            <th role="columnheader"  x-bind="bind.col_header" data-field="telegram_id"
              class="border-l border-gray-300 pl-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <div class="flex items-center justify-between relative">
                <p class="text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                  TELEGRAM ID
                </p>
                <button role="button" aria-label="option" class="ml-1 mr-1 text-gray-800 dark:text-gray-100 rounded">
                  <template x-if="sorting.telegram_id.order==='asc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-down" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" />
                      <polyline points="6 9 12 15 18 9" />
                    </svg>
                  </template>
                  <template x-if="sorting.telegram_id.order==='desc'">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chevron-up" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <polyline points="6 15 12 9 18 15"></polyline>
                    </svg>
                  </template>
                </button>
                <span class="bg-gray-500 text-white text-xs px-1 mr-3 rounded" x-show="sorting.telegram_id.priority!==null" x-text="sorting.telegram_id.priority"></span>
              </div>
            </th>
            <th role="columnheader"
              class="border-l border-gray-300 px-4 whitespace-nowrap w-32 first-dropdown cursor-pointer">
              <p class="text-gray-800 dark:text-gray-100 font-normal text-center text-xs tracking-normal leading-4">
                Action
              </p>
            </th>
          </tr>
        </thead>
        <tbody x-bind="bind.table_body">
          <template x-for="(row,idx) in $store.user.current_data" :key="row.id">
            <tr class="border-b border-gray-300">
              <td class="pl-3 w-24 py-3">
                <div class="flex items-center">
                  <input placeholder="check box" type="checkbox"
                    :id="'checkrow_'+idx"
                    :data-idx="idx" :data-id="row.id" x-bind="bind.row_checkbox" :checked="row.checked===true"
                    class="checkrow cursor-pointer relative w-5 h-5 border rounded border-gray-400 bg-white" />
                </div>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.id"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.username"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.full_name"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.email"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class="whitespace-nowrap text-center">
                <div class="relative inline-block w-12 mr-2 align-middle select-none transition duration-200 ease-in">
                  <input type="checkbox"
                    class="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer" :checked="_.toInteger(row.status)===1" :data-idx="idx" x-bind="bind.col_status"/>
                  <label for="toggle"
                    class="toggle-label block overflow-hidden h-6 rounded-full bg-gray-300"></label>
                </div>
              </td>
              <td class="whitespace-nowrap text-center">
                <div class="relative inline-block w-12 mr-2 align-middle select-none transition duration-200 ease-in">
                  <input type="checkbox"
                    class="toggle-checkbox absolute block w-6 h-6 rounded-full bg-white border-4 appearance-none cursor-pointer" :checked="_.toInteger(row.is_organic)===1" :data-idx="idx" x-bind="bind.col_is_organic"/>
                  <label for="toggle"
                    class="toggle-label block overflow-hidden h-6 rounded-full bg-gray-300"></label>
                </div>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.mobile_no"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.employ_nik"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.spv_nik"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class=" pl-4 whitespace-nowrap">
                <p
                  x-text="row.telegram_id"
                  class="whitespace-nowrap text-gray-800 dark:text-gray-100 font-normal text-left text-xs tracking-normal leading-4">
                </p>
              </td>
              <td class="whitespace-nowrap w-60">
                <div class="flex gap-x-2 flex-nowrap justify-center">
                  <button
                    class="focus:ring-2 focus:ring-red-400 hover:bg-red-100 border-red-800 p-1 cursor-pointer text-red-800 dark:text-red-100 border rounded focus:outline-none"
                    role="button" :data-idx="idx" x-bind="bind.col_act_remove">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <line x1="4" y1="7" x2="20" y2="7"></line>
                      <line x1="10" y1="11" x2="10" y2="17"></line>
                      <line x1="14" y1="11" x2="14" y2="17"></line>
                      <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path>
                      <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path>
                    </svg>
                  </button>
                  <button
                    class="focus:ring-2 focus:ring-indigo-400 hover:bg-indigo-100 border-indigo-800 p-1 cursor-pointer text-indigo-800 dark:text-indigo-100 border rounded focus:outline-none"
                    role="button" @click="$dispatch('show-edit', idx)">
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="16"
                      height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                      stroke-linecap="round" stroke-linejoin="round">
                      <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                      <path d="M9 7h-3a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-3"></path>
                      <path d="M9 15h3l8.5 -8.5a1.5 1.5 0 0 0 -3 -3l-8.5 8.5v3"></path>
                      <line x1="16" y1="5" x2="19" y2="8"></line>
                    </svg>
                  </button>
                </div>
              </td>
            </tr>
          </template>
        </tbody>
      </table>
    </div>
  </div>
  <div x-data="paging" class="pr-5 mx-auto full-container pt-8 flex justify-end items-center pb-8">
    <a x-bind="bind.prev_btn" x-show="$store.paging.data.current_page>1 && $store.user.current_data.length>0" class="cursor-pointer text-gray-600 mr-5 border-gray-200 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
      role="link" aria-label="previous page">
      <svg xmlns="http://www.w3.org/2000/svg" class="dark:text-gray-100 icon icon-tabler icon-tabler-chevron-left"
        width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
        stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z"></path>
        <polyline points="15 6 9 12 15 18"></polyline>
      </svg>
    </a>
    <p class="text-gray-800 dark:text-gray-100 fot-normal text-xs">Page</p>
    <label class="hidden"></label>
    <input x-bind="bind.page_input" placeholder="0" x-model="$store.paging.data.current_page" type="text"
      class="bg-white text-center dark:bg-gray-800 w-10 px-2 mx-2 text-gray-800 dark:text-gray-100 focus:outline-none focus:border focus:border-indigo-700 font-normal flex items-center text-xs border-gray-300 rounded border" />
    <!-- <p class="text-gray-800 dark:text-gray-100 fot-normal text-xs">of <span x-text="$store.paging.data.total_page"></span></p> -->
    <a x-bind="bind.next_btn" x-show="hasNext" class="cursor-pointer text-gray-600 mx-5 border-gray-200 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
      role="link" aria-label="next page">
      <svg xmlns="http://www.w3.org/2000/svg" class="dark:text-gray-100 icon icon-tabler icon-tabler-chevron-right"
        width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none"
        stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z"></path>
        <polyline points="9 6 15 12 9 18"></polyline>
      </svg>
    </a>
    <label class="hidden"></label>
    <input x-bind="bind.limit_input" placeholder="0" x-model="$store.paging.data.limit" type="text"
      class="bg-white text-center dark:bg-gray-800 w-10 px-2 mx-2 text-gray-800 dark:text-gray-100 focus:outline-none focus:border focus:border-indigo-700 font-normal flex items-center text-xs border-gray-300 rounded border" />
    <p class="-mt-1 text-gray-800 dark:text-gray-100 fot-normal text-xs">per page</p>
  </div>
  <?=$me->partial('index/modal.phtml', []);?>
</div>