<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $me
 */
$me = $this;
$ini_reader = new \Laminas\Config\Reader\Ini();
$conf = $ini_reader->fromFile(conf_path() . env('APPLICATION_ENV') . ".conf");
$app_conf = $conf['app-config'];
?>
<div class="bg-gray-900 h-screen">
  <div class="relative overflow-hidden">
    <main>
      <div class="pt-10 bg-gray-900 sm:pt-16 lg:pt-8 lg:pb-14 lg:overflow-hidden">
        <div class="mx-auto max-w-7xl lg:px-8">
          <div class="lg:grid lg:grid-cols-2 lg:gap-8">
            <div class="mx-auto my-18 py-20 max-w-md px-4 sm:max-w-2xl sm:px-6 sm:text-center lg:px-0 lg:text-left lg:flex lg:items-center">
              <div class="lg:py-24">
                <h1 class="mt-4 text-6xl tracking-tight font-extrabold text-white">
                  <span class="block">EBIS Profitability Analytics Platform</span>
                  <span class="pb-3 block bg-clip-text text-2xl text-transparent bg-gradient-to-r from-teal-200 to-cyan-400 sm:pb-5">for Healthy Business Monitoring in CFUE</span>
                </h1>
                <p class="text-base text-gray-300 sm:text-xl lg:text-lg xl:text-xl">
                  Welcome to new EBIS Profitability Analytics Platform.
                </p>
                <div class="mt-10 sm:mt-12">
                  <div class="sm:flex">
                    <div class="mt-3 mx-auto lg:mx-0 w-full text-center">
                      <a href="/auth/logout" type="submit" class="block w-full py-3 px-4 rounded-md shadow bg-gradient-to-r from-teal-500 to-cyan-600 text-white font-medium hover:from-teal-600 hover:to-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-400 focus:ring-offset-gray-900">Sign Out</a>
                    </div>
                  </div>
                  <p class="mt-3 text-sm text-gray-300 sm:mt-4 mb-5">still on developing process</p>
                </div>
              </div>
            </div>
            <div class="mt-12 -mb-16 sm:-mb-48 lg:m-0 lg:relative">
              <div class="mx-auto max-w-md px-4 sm:max-w-2xl sm:px-6 lg:max-w-none lg:px-0">
                <!-- Illustration taken from Lucid Illustrations: https://lucid.pixsellz.io/ -->
                <img class="w-full -translate-y-32 lg:translate-y-14 lg:absolute lg:inset-y-0 lg:left-0 lg:h-full lg:w-auto lg:max-w-none" src="https://tailwindui.com/img/component-images/cloud-illustration-teal-cyan.svg" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</div>
