<div x-bind="event" x-cloak x-show="show" x-data="filter_user" class="z-50 fixed w-full flex justify-center inset-0">
    <div @click="" class="w-full h-full bg-bluegray-900 bg-opacity-70 z-0 absolute inset-0"></div>
    <div class="mx-auto container">
        <div class=" flex items-center justify-center h-full w-full">
            <div class="w-3/6 bg-white rounded-md shadow fixed  sm:h-aut">
                <div class="px-5 py-4">
                    <div class="xl:w-full border-b border-gray-300 dark:border-gray-700 pb-2">
                        <div class="flex items-center w-11/12 ">
                            <div class="container mx-auto">
                                <div class="mx-auto xl:w-full">
                                    <h1 role="heading" class="text-lg text-gray-800 dark:text-gray-100 font-bold">Filter User</h1>
                                    <p class="text-sm text-gray-500 dark:text-gray-400 pt-1"></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="text-xs px-6 w-full max-h-72 overflow-y-auto scrollbar scrollbar-thumb-bluegray-400 scrollbar-track-bluegray-100 scrollbar-thin">
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left font-bold">
                                <span>FIELD</span>
                            </div>
                            <div class="w-2/5 text-center font-bold">
                                <span>CONDITION</span>
                            </div>
                            <div class="w-2/5 text-center font-bold">
                                <span>VALUE (comma separated)</span>
                            </div>
                        </div>
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left">
                                <span>USER ID</span>
                            </div>
                            <div class="w-2/5 text-center">
                                <select x-model="data.condition_uid" class="w-full p-3 mt-3  border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800">
                                    <option value="none">None</option>
                                    <option value="equal">Equal</option>
                                    <option value="not equal">Not Equal</option>
                                </select>
                            </div>
                            <div class="w-2/5 text-center">
                                <input x-model="data.val_uid" id="filter_uid" name="" class="p-3 mt-3 leading-none rounded focus:outline-none focus:border-gray-600 text-sm font-medium  text-gray-800" />
                            </div>
                        </div>
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left">
                                <span>USERNAME</span>
                            </div>
                            <div class="w-2/5 text-center">
                                <select x-model="data.condition_uname" class="w-full p-3 mt-3  border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800">
                                    <option value="none">None</option>
                                    <option value="equal">Equal</option>
                                    <option value="not equal">Not Equal</option>
                                </select>
                            </div>
                            <div class="w-2/5 text-center">
                                <input x-model="data.val_uname" id="filter_uname" name="" class="p-3 mt-3 leading-none rounded focus:outline-none focus:border-gray-600 text-sm font-medium  text-gray-800" />
                            </div>
                        </div>
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left">
                                <span>FULL NAME</span>
                            </div>
                            <div class="w-2/5 text-center">
                                <select x-model="data.condition_full_name" class="w-full p-3 mt-3  border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800">
                                    <option value="none">None</option>
                                    <option value="equal">Equal</option>
                                    <option value="not equal">Not Equal</option>
                                </select>
                            </div>
                            <div class="w-2/5 text-center">
                                <input x-model="data.val_full_name" id="filter_fullname" name="" class="p-3 mt-3 leading-none rounded focus:outline-none focus:border-gray-600 text-sm font-medium  text-gray-800" />
                            </div>
                        </div>
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left">
                                <span>E-MAIL</span>
                            </div>
                            <div class="w-2/5 text-center">
                                <select x-model="data.condition_email" class="w-full p-3 mt-3  border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800">
                                    <option value="none">None</option>
                                    <option value="equal">Equal</option>
                                    <option value="not equal">Not Equal</option>
                                </select>
                            </div>
                            <div class="w-2/5 text-center">
                                <input x-model="data.val_email" id="filter_email" name="" class="p-3 mt-3 leading-none rounded focus:outline-none focus:border-gray-600 text-sm font-medium  text-gray-800" />
                            </div>
                        </div>
                        <div class="md:flex gap-x-2 items-center mt-4 w-full">
                            <div class="w-1/5 text-left">
                                <span>STATUS</span>
                            </div>
                            <div class="w-2/5 text-center">
                                <select x-model="data.val_status" class="w-full p-3 mt-3  border rounded border-gray-200 focus:outline-none focus:border-gray-600 text-sm font-medium leading-none text-gray-800">
                                    <option value="none">None</option>
                                    <option value="1">Active</option>
                                    <option value="0">Not Active</option>
                                </select>
                            </div>
                            <div class="w-2/5 text-center">

                            </div>
                        </div>
                    </div>
                    <div class="flex items-center justify-end mt-10 gap-x-2">
                        <button @click="hideModal()" role="button" aria-label="closebutton" class="focus:ring-2 focus:ring-offset-2 focus:bg-gray-600 focus:ring-gray-500 focus:outline-none px-3 py-1 bg-gray-500 hover:bg-gray-400 shadow rounded text-sm text-white">Cancel</button>
                        <button @click="submit()" aria-label="add user" role="button" class="focus:ring-2 focus:ring-offset-2 focus:ring-green-800 focus:outline-none px-3 py-1 bg-green-700 hover:bg-opacity-80 shadow rounded text-sm text-white">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>