<div class="flex w-full pl-3 sm:pl-6 pr-3 py-5 items-center justify-between bg-mygreen/30 rounded-t">
  <h3 class="text-mygreen-dark font-bold text-base sm:text-xl">List of User</h3>
  <div class="flex">
    <button
      class="ml-0 sm:ml-6 bg-blue-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-700 hover:bg-blue-600 rounded text-white px-3 h-8 flex items-center text-sm"><i
        class="ri-upload-2-fill mr-2"></em>Upload User</button>
    <button
      class="ml-0 sm:ml-6 bg-green-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-700 hover:bg-green-600 rounded text-white px-3 h-8 flex items-center text-sm"><i
        class="ri-user-add-fill mr-2"></em>Create User</button>
  </div>
</div>
<div class="flex flex-col md:flex-row p-3 justify-between items-start md:items-stretch w-full">
  <div class="w-full md:w-1/3 flex flex-col md:flex-row items-start md:items-center">
    <div class="flex items-center">
      <button
        class="focus:ring-2 focus:ring-offset-2 hover:bg-red-600/80 hover:text-white focus:ring-red-600 p-2 border-gray-200 text-gray-600 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
        aria-label="Delete table" role="button">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon cursor-pointer icon-tabler icon-tabler-trash" width="20"
          height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
          stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" />
          <line x1="4" y1="7" x2="20" y2="7" />
          <line x1="10" y1="11" x2="10" y2="17" />
          <line x1="14" y1="11" x2="14" y2="17" />
          <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
          <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
        </svg>
      </button>
      <button
        class="focus:ring-2 focus:ring-offset-2 hover:bg-indigo-600/80 hover:text-white focus:ring-indigo-600 text-gray-600 p-2 ml-2 border-gray-200 dark:text-gray-400 border rounded focus:outline-none focus:border-gray-800 focus:shadow-outline-gray"
        aria-label="upload Table" role="button">
        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-download" width="20" height="20"
          viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
          stroke-linejoin="round">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2 -2v-2" />
          <polyline points="7 11 12 16 17 11" />
          <line x1="12" y1="4" x2="12" y2="16" />
        </svg>
      </button>
    </div>
  </div>
  <div class="w-full md:w-2/3 flex flex-col md:flex-row items-start md:items-center justify-end">
    <div class="flex flex-col w-full sm:w-1/2 md:ml-4 mt-3 md:mt-0">
      <div class="relative w-full">
        <div aria-hidden="true"
          class="absolute cursor-pointer text-gray-600 dark:text-gray-400 flex items-center pr-3 right-0 border-l h-full hover:bg-blue-600/80 hover:text-white focus:ring-blue-600">
          <span class="ml-2 mr-1">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-filter" width="20" height="20"
              viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
              stroke-linejoin="round">
              <path stroke="none" d="M0 0h24v24H0z"></path>
              <path d="M5.5 5h13a1 1 0 0 1 0.5 1.5L14 12L14 19L10 16L10 12L5 6.5a1 1 0 0 1 0.5 -1.5">
              </path>
            </svg>
          </span>
          <span class="text-sm leading-tight tracking-normal">Filter</span>
        </div>
        <div class="absolute text-gray-600 dark:text-gray-400 flex items-center pl-3 h-full">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-search" width="16" height="16"
            viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round"
            stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z"></path>
            <circle cx="10" cy="10" r="7"></circle>
            <line x1="21" y1="21" x2="15" y2="15"></line>
          </svg>
        </div>
        <label for="search" class="hidden text-gray-800 text-sm font-bold leading-tight tracking-normal mb-2"></label>
        <input id="search"
          class="w-full text-gray-600 bg-transparent dark:bg-gray-800 dark:text-gray-400 focus:outline-none focus:border focus:border-blue-600 font-normal pl-8 pr-24 h-10 flex items-center text-sm border-gray-300 dark:border-gray-200 rounded border"
          placeholder="Search by project name or owner" />
      </div>
    </div>
  </div>
</div>