<div class="bg-white dark:bg-gray-800 px-8 py-6">
  <ul class="grid grid-cols-1 gap-6 grid-cols-3">
    <li class="col-span-1 bg-white rounded-lg shadow divide-y divide-gray-200">
      <div class="w-full flex items-center justify-between p-3 space-x-6">
        <div class="flex-1 truncate">
          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-lg font-medium truncate">
              Role Name</h3>
            <span
              class="flex-shrink-0 inline-block px-2 py-0.5 text-green-800 text-xs font-medium bg-green-100 rounded-full">Main</span>
            <span
              class="flex-shrink-0 inline-block px-2 py-0.5 text-green-800 text-xs font-medium bg-green-100 rounded-full">Active</span>
          </div>
          <p class="text-gray-500 text-xs truncate mb-5">Role Code</p>

          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-xs font-medium truncate">
              Code: </h3>
            <p class="text-gray-500 text-xs truncate">Role Code</p>
          </div>

          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-xs font-medium truncate">
              Redirect Route: </h3>
            <p class="text-gray-500 text-xs truncate">Redirect Route
            </p>
          </div>

          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-xs font-medium truncate">
              Redirect Param: </h3>
            <p class="text-gray-500 text-xs truncate">Redirect Param
            </p>
          </div>

          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-xs font-medium truncate">
              Redirect URL: </h3>
            <p class="text-gray-500 text-xs truncate">Redirect URL
            </p>
          </div>

          <div class="flex items-center space-x-3">
            <h3 class="text-gray-900 text-xs font-medium truncate">
              Redirect Query: </h3>
            <p class="text-gray-500 text-xs truncate">Redirect Query
            </p>
          </div>
        </div>
      </div>
      <div>
        <div class="-mt-px flex divide-x divide-gray-200">
          <div class="w-0 flex-1 flex">
            <a
              class="relative -mr-px w-0 flex-1 inline-flex items-center justify-center py-2 text-sm text-gray-700 font-medium border border-transparent rounded-bl-lg hover:text-white hover:bg-red-600/60 cursor-pointer">
              <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"
                aria-hidden="true">
                <path fill-rule="evenodd"
                  d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z"
                  clip-rule="evenodd" />
              </svg>
              <span class="ml-1">Remove</span>
            </a>
          </div>
          <div class="-ml-px w-0 flex-1 flex">
            <a href="tel:+1-202-555-0170"
              class="relative w-0 flex-1 inline-flex items-center justify-center py-2 text-sm text-gray-700 font-medium border border-transparent rounded-br-lg hover:text-white hover:bg-gray-500/60">
              <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                  clip-rule="evenodd" />
              </svg>
              <span class="ml-3">Disable</span>
            </a>
          </div>
        </div>
      </div>
    </li>
  </ul>

</div>