<div class="flex px-10 w-full text-gray-800 dark:text-gray-100 py-3 bg-gray-100 dark:bg-gray-700">
  <div class="flex-grow align-middle justify-between">
    <h1 class="text-lg" x-text="title[tab]+' Information'"></h1>
  </div>
  <div class="flex-grow text-right align-middle">
    <template x-if="tab===1">
      <div class="flex flex-row-reverse">
        <button
          class="sm:ml-6 bg-green-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-700 hover:bg-green-600 rounded text-white px-2 h-6 flex items-center text-xs"><i
            class="ri-save-3-line mr-2"></em>Save Data</button>
        <button
          class="sm:ml-6 bg-blue-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-700 hover:bg-blue-600 rounded text-white px-2 h-6 flex items-center text-xs"><i
            class="ri-add-line mr-2"></em>Add Role</button>
      </div>
    </template>
    <template x-if="tab===2">
      <div class="flex flex-row-reverse">
        <button
          class="sm:ml-6 bg-green-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-700 hover:bg-green-600 rounded text-white px-2 h-6 flex items-center text-xs"><i
            class="ri-save-3-line mr-2"></em>Save Data</button>
      </div>
    </template>
    <template x-if="tab===3">
      <div class="flex flex-row-reverse  align-middle">
        <button
          @click="console.log(row.id,selected_module,row.selected_menu)"
          class="sm:ml-6 bg-green-700 transition duration-150 ease-in-out focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-700 hover:bg-green-600 rounded text-white px-2 h-6 flex items-center text-xs align-middle"><i
            class="ri-save-3-line mr-2"></em>Save Data</button>
        <select x-model="selected_module"
          class="form-select hover:border-mygreen focus:border-mygreen px-2 h-6 focus:ring-mygreen block text-xs p-1 align-middle w-32">
          <template x-for="mdl in module_data">
            <option :value="mdl.id" class="pr-2" x-text="mdl.name"></option>
          </template>
        </select>

        <label class="mr-2">Module</label>
      </div>
    </template>
  </div>
</div>