<?php
$me = $this;
$ini_reader = new \Laminas\Config\Reader\Ini();
$conf = $ini_reader->fromFile(conf_path() . env('APPLICATION_ENV') . ".conf");
$app_conf = $conf['app-config'];
$identity = $me->identity();
/** @var Core\Helper\Layout\ISMLeftNav $layoutHelper */
$layoutHelper = $me->ISMLeftNavLayout();
$layoutHelper->generateMenu($identity, $me->_module);
/** @var Core\Helper\View\Routing $routingHelper */
$routingHelper = $me->Routing();
?>
<!-- Sidebar -->
<aside class="flex-shrink-0 hidden w-64 bg-white border-r dark:border-primary-darker dark:bg-darker md:block">
  <div class="flex flex-col h-full">
    <!-- Sidebar links -->
    <nav aria-label="Main" class="flex-1 px-2 py-4 space-y-2 overflow-y-hidden hover:overflow-y-auto">
      <?= $layoutHelper->generateSideBar($me); ?>
    </nav>

    <!-- Sidebar footer -->
    <div class="flex-shrink-0 px-2 py-4 space-y-2">
      <button
        @click="openSettingsPanel"
        type="button"
        class="flex items-center justify-center w-full px-4 py-2 text-sm text-white rounded-md bg-primary hover:bg-primary-dark focus:outline-none focus:ring focus:ring-primary-dark focus:ring-offset-1 focus:ring-offset-white dark:focus:ring-offset-dark"
      >
        <span aria-hidden="true">
          <svg
            class="w-4 h-4 mr-2"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
            />
          </svg>
        </span>
        <span>Customize</span>
      </button>
    </div>
  </div>
</aside>